### ISSUE TITLE
Wrong markup for card example

### ISSUE THREAD

**Issue by hudochenkov** [dropbox/scooter#1]
[Cards example](http://dropbox.github.io/scooter/components.html#cards). `<p>` contains `<div class="c-card">`. But it can't by specification. DOM breaks:

![image](https://cloud.githubusercontent.com/assets/654597/10970388/5f9ae602-83df-11e5-9f74-2b328db3aa4d.png)

**Comment by daneden** [comment]
Hmm, this looks like an issue with the way Middleman is rendering the code example function. I’ll investigate. Thanks!
