### ISSUE TITLE
Tab-Nav Inquiry

### ISSUE THREAD

**Issue by raybesiga** [dropbox/scooter#20]
Hello Dropbox,

Really cool project. I really like the clean, lean feel that this presents. Just inquiring about the tab navs. What is the structure to the body of the tabs besides the links? Is the structure similar to Bootstrap? If not, how does it differ? 

Thanks and cheers.

**Comment by daneden** [comment]
Hey @raybesiga! Since Scooter is (currently, at least) free of JS, there’s not any documented structure for the tab contents themselves. However, the tabs are in use in Dropbox product—I’ll see if I can boil down the logic used in production to include it in Scooter.
