### ISSUE TITLE
Button groups

### ISSUE THREAD

**Issue by jnu** [dropbox/scooter#22]
Would be great to have support for button groups, especially if they work with radio inputs (as in [bootstrap](http://getbootstrap.com/components/#btn-groups))

**Comment by daneden** [comment]
@jnu thanks for opening an issue on this! Here’s a demo/proposition for the button groups: http://codepen.io/daneden/pen/4196c30ee453894327413045b1ff7524

**Comment by jnu** [comment]
looks great to me! will the convention be to use `primary` for the active buttons and `secondary` for other buttons then?

**Comment by daneden** [comment]
@jnu I think the concept of active and inactive buttons is another discussion, but I just added an MVP for button groups!
