### ISSUE TITLE
Missing `!default` in `variables/_config.scss`

### ISSUE THREAD

**Issue by lennartjansson** [dropbox/scooter#23]
Hi Dan :)

`$DBimage-path` is the only variable I had to change in the Scooter source with the way we're using it in Lighthouse (webpack was looking for the images in the wrong place). It should have `!default` so the image path can be overriden in user styles, right?

**Comment by daneden** [comment]
Good catch! Feel free to open a PR to fix this or I’ll try to get on it ASAP.
